export enum ETicketFields {
  _ID = '_id',
  URL = 'url',
  EXTERNAL_ID = 'external_id',
  CREATED_AT = 'created_at',
  TYPE = 'type',
  SUBJECT = 'subject',
  DESCRIPTION = 'description',
  PRIORITY = 'priority',
  STATUS = 'status',
  RECIPIENT = 'recipient',
  SUBMITTER_ID = 'submitter_id',
  ASSIGNEE_ID = 'assignee_id',
  ORGANIZATION_ID = 'organization_id',
  TAGS = 'tags',
  HAS_INCIDENTS = 'has_incidents',
  DUE_AT = 'due_at',
  VIA = 'via',
  REQUESTER_ID = 'requester_id'
}
