export enum EUserFields {
  _ID = '_id',
  URL = 'url',
  EXTERNAL_ID = 'external_id',
  NAME = 'name',
  ALIAS = 'alias',
  CREATED_AT = 'created_at',
  ACTIVE = 'active',
  VERIFIED = 'verified',
  SHARED = 'shared',
  LOCALE = 'locale',
  TIMEZONE = 'timezone',
  LAST_LOGIN_AT = 'last_login_at',
  EMAIL = 'email',
  PHONE = 'phone',
  SIGNATURE = 'signature',
  ORGANIZATION_ID = 'organization_id',
  TAGS = 'tags',
  SUSPENDED = 'suspended',
  ROLE = 'role'
}
